name: Check I18N Changes

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-i18n:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run I18N module
        run: |
          poetry run python -m norminette.i18n

      - name: Check for changes in .po files
        run: |
          if git status --porcelain | grep -E '\.po$'; then
            echo "I18N files have been modified. Please run 'python -m norminette.i18n' and commit the changes."
            exit 1
          else
            echo "No changes detected in I18N files."
          fi
